analytics: {}
color:
  brandColors:
    - '#90A8C0'
    - '#082058'
    - '#6888A8'
    - '#0828A0'
    - '#A8C0E0'
  brandStrength: 0.79054
  lightness: 0.541016
  rhythmicContrast: 0.466216
  saturation: 0.496621
cta: {}
layout_spectrum: 1
name: markdeli
opengraph: {}
purpose: {}
typography_spectrum: 0.212837
